name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      - name: Install luacheck
        run: luarocks install luacheck
      - name: lint
        run: luacheck src
