name: unit-tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version: ['5.1', '5.2', '5.3', '5.4', 'luajit']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python and hererocks
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: pip install git+https://github.com/luarocks/hererocks
      - uses: actions/cache@v2
        id: cache
        with:
          path: .env
          key: ${{ runner.os }}-${{ hashFiles('.env/hererocks.manifest') }}
      - name: Install lua
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          hererocks .env --lua ${{ matrix.lua-version }} --luarocks latest
          source .env/bin/activate
          luarocks install struct
          luarocks install inspect
          luarocks install busted
          luarocks install luacov 
      - run: |
          source .env/bin/activate
          busted --coverage --output plainTerminal
          luacov src
