name: unit-tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version: ['lua 5.1', 'lua 5.2', 'lua 5.3', 'lua 5.4', 'luajit 2.0']
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./.env
          key: ${{ runner.os }}-${{ matrix.lua-version }}-${{ secrets.CACHE_VERSION }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install hererocks
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install git+https://github.com/luarocks/hererocks
      - name: Install lua
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          hererocks .env --${{ matrix.lua-version }} --luarocks latest
          source .env/bin/activate
          luarocks install inspect
          luarocks install busted
          luarocks install luacov 
          luarocks install luacov-reporter-lcov
          exit 0
      - name: Run tests
        run: |
          source .env/bin/activate
          busted --coverage --output plainTerminal
          luacov -r lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./luacov.report.out
